In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lectura de datos de Falabella

In [ ]:
df_falabella = pd.read_csv('/content/drive/MyDrive/retail_iphone/productos_falabella.csv')
df_falabella = df_falabella.rename(columns = {'Modelo': 'modelo', 'Precio Normal': 'precio_normal', 'Precio Oferta': 'precio_oferta'})
df_falabella

# Lectura de datos Paris

In [ ]:
df_paris = pd.read_excel('/content/drive/MyDrive/retail_iphone/paris_iphone.xlsx')
df_paris

In [ ]:
df_paris = df_paris[~df_paris['modelo'].str.contains('reacondicionado', case=False, na=False)]
df_paris

# Lectura de datos WOM

In [ ]:
df_wom = pd.read_excel('/content/drive/MyDrive/retail_iphone/apple_wom.xlsx')
df_wom = df_wom.rename(columns = {'LABEL-1': 'marca', 'LABEL-2': 'modelo','LABEL-3': 'precio_normal', 'LABEL-4': 'precio_oferta'})
df_wom

# Lectura de datos Hites

In [ ]:
df_hites = pd.read_csv('/content/drive/MyDrive/retail_iphone/productos_hites - esteban.csv')
df_hites = df_hites.rename(columns = {'marca y modelo': 'modelo','precio normal': 'precio_normal', 'precio oferta': 'precio_oferta'})

In [ ]:
df_hites

# Lectura de datos La Polar

In [ ]:
df_polar = pd.read_csv('/content/drive/MyDrive/retail_iphone/productos_lapolar - esteban.csv')
df_polar = df_polar.rename(columns = {'Modelo': 'modelo','precio normal': 'precio_normal', 'precio oferta': 'precio_oferta'})

In [ ]:
df_polar

# Lectura de datos Mercado Libre

In [ ]:
df_mercado_libre = pd.read_csv('/content/drive/MyDrive/retail_iphone/productos_mercadolibre.csv')
df_mercado_libre = df_mercado_libre.rename(columns = {'Modelo': 'modelo', 'Precio Normal': 'precio_normal', 'Precio Oferta': 'precio_oferta'})
df_mercado_libre

# Lectura de datos PC factory

In [ ]:
df_factory = pd.read_csv('/content/drive/MyDrive/retail_iphone/Pcfactory.csv', delimiter=';')
df_factory

#Lectura de datos Lider

In [ ]:
df_lider = pd.read_csv('/content/drive/MyDrive/retail_iphone/productos_lider.csv')
df_lider = df_lider.rename(columns = {'nombre' : 'modelo', 'precio normal': 'precio_normal' , 'precio oferta': 'precio_oferta'})
df_lider

#Agregamos la tienda donde es vendido el producto

In [ ]:
df_falabella['tienda'] = 'falabella'
df_paris['tienda'] = 'paris'
df_wom['tienda'] = 'wom'
df_hites['tienda'] = 'hites'
df_polar['tienda'] = 'la polar'
df_mercado_libre['tienda'] = 'mercado libre'
df_factory['tienda'] = 'pcfactory'
df_lider['tienda'] = 'lider'

# Unimos los datos en un solo, con la informaci√≥n relevante.

In [ ]:
df_final = pd.concat([df_falabella, df_paris, df_wom, df_hites, df_polar, df_mercado_libre, df_factory, df_lider], axis = 0 , ignore_index=True)

In [ ]:
df_final = df_final.drop(['marca'], axis=1)
df_final

# Guardamos los Datos

In [ ]:
df_final.to_csv('datos_finales.csv')

# Datos limpios

desde aca se trabaja con datos limpiados (lo hizo belen)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/retail_iphone/dataLimpia.csv')
df

In [ ]:
df['modelo'] = df['modelo'].str.lower()
df

In [ ]:
df['tienda'].unique()

In [ ]:
df['precio_normal'] = df['precio_normal'].replace('[\$,\.]', '', regex=True).str.strip().astype(float)
df['precio_oferta'] = df['precio_oferta'].replace('[\$,\.]', '', regex=True).str.strip().astype(float)

In [ ]:
df.to_csv('final_final.csv')

In [3]:
df = pd.read_csv('final_final.csv')
df

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda
0,0,iphone 15 pro max 256gb,1349990.0,819990.0,falabella
1,1,iphone 15 128gb,849990.0,819990.0,falabella
2,2,iphone 15 pro max 512gb,1499990.0,1079990.0,falabella
3,3,iphone 11 128gb,429990.0,1079990.0,falabella
4,4,iphone 15 pro 128gb,1129990.0,1079990.0,falabella
...,...,...,...,...,...
94,94,iphone 13 5g 256gb gris apple,899990.0,689990.0,lider
95,95,iphone 14 5g 128gb blanco,899990.0,699990.0,lider
96,96,iphone 14 5g 128gb negro,899990.0,699990.0,lider
97,97,iphone 14 plus 5g 256gb blanco apple,1229990.0,889990.0,lider
98,98,iphone 15 pro 5g 512gb negro apple,1729990.0,1359990.0,lider

In [4]:
df_iphone_11 = df[df['modelo'].str.contains('iphone 11')]
df_iphone_11

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda
3,3,iphone 11 128gb,429990.0,1079990.0,falabella
19,19,iphone 11 64gb¬†blanco,399990.0,379990.0,paris
24,24,iphone 11 64gb negro,399990.0,379990.0,paris
41,41,iphone 11 negro / 64 gb / claro,699990.0,399990.0,hites
42,42,iphone 11 negro / 64 gb / liberado,699990.0,399990.0,hites
43,43,iphone 11 negro / 64 gb / wom,699990.0,399990.0,hites
56,56,"celular apple iphone 11 64gb 6,1"" negro libera...",499990.0,379990.0,la polar
84,84,apple iphone 11 (64 gb) - negro - distribuidor...,669990.0,359990.0,mercado libre
85,85,apple iphone 11 (64 gb) - blanco - distribuido...,669990.0,359990.0,mercado libre
92,92,iphone 11 4g 64gb negro apple,469990.0,349990.0,lider

In [5]:
df_iphone_12 = df[df['modelo'].str.contains('iphone 12')]
df_iphone_12

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda
10,10,iphone 12 128gb,499990.0,479990.0,falabella
15,15,iphone 12 128gb blanco,499990.0,479990.0,paris
16,16,iphone 12 128gb negro,499990.0,479990.0,paris
35,35,iphone 12 128gb,799990.0,480000.0,wom
44,44,iphone 12 blanco / 5g / 128 gb / liberado,799990.0,529990.0,hites
74,74,apple iphone 12 (128 gb) - morado - distribuid...,949990.0,625990.0,mercado libre

In [6]:
df_iphone_13 = df[df['modelo'].str.contains('iphone 13')]
df_iphone_13

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda
8,8,iphone 13 128gb,619990.0,589990.0,falabella
37,37,iphone 13 128gb,889990.0,660000.0,wom
45,45,iphone 13 negro / 5g / 128 gb / liberado,869990.0,679990.0,hites
46,46,iphone 13 negro / 5g / 256 gb / liberado,929990.0,729990.0,hites
58,58,"celular apple iphone 13 256gb 6,1"" medianoche ...",939990.0,699990.0,la polar
67,67,apple iphone 13 (512 gb) - rosa - distribuidor...,1199990.0,869990.0,mercado libre
68,68,apple iphone 13 (512 gb) - azul - distribuidor...,1199990.0,869990.0,mercado libre
70,70,apple iphone 13 (512 gb) - azul medianoche - d...,1199990.0,869990.0,mercado libre
76,76,apple iphone 13 (512 gb) - blanco estelar - di...,1199990.0,869990.0,mercado libre
80,80,apple iphone 13 (512 gb) - (product)red - dist...,1199990.0,869990.0,mercado libre
93,93,iphone 13 5g 128gb negro apple,869990.0,589990.0,lider
94,94,iphone 13 5g 256gb gris apple,899990.0,689990.0,lider

In [7]:
df_iphone_14 = df[df['modelo'].str.contains('iphone 14')]
df_iphone_14

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda
6,6,iphone 14 256gb,929990.0,719990.0,falabella
7,7,iphone 14 128gb,739990.0,719990.0,falabella
22,22,iphone 14 128gb morado,729990.0,699990.0,paris
27,27,iphone 14 128gb color medianoche,729990.0,699990.0,paris
31,31,iphone 14 128gb blanco estelar,729990.0,699990.0,paris
36,36,iphone 14 5g 128gb,949990.0,720000.0,wom
47,47,iphone 14 blanco / 5g / 128 gb / liberado,949990.0,699990.0,hites
48,48,iphone 14 negro / 5g / 128 gb / liberado,949990.0,749990.0,hites
49,49,iphone 14 plus negro / 5g / 256 gb / liberado,1249990.0,899990.0,hites
55,55,"celular apple iphone 14 128gb 6,1"" medianoche ...",949990.0,719990.0,la polar
66,66,apple iphone 14 (256 gb) - azul - distribuidor...,1099990.0,848990.0,mercado libre
86,86,apple iphone 14 (256 gb) - (product)red - dist...,1099990.0,789990.0,mercado libre
95,95,iphone 14 5g 128gb blanco,899990.0,699990.0,lider
96,96,iphone 14 5g 128gb negro,899990.0,699990.0,lider
97,97,iphone 14 plus 5g 256gb blanco apple,1229990.0,889990.0,lider

In [8]:
df_iphone_15 = df[df['modelo'].str.contains('iphone 15')]
df_iphone_15

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda
0,0,iphone 15 pro max 256gb,1349990.0,819990.0,falabella
1,1,iphone 15 128gb,849990.0,819990.0,falabella
2,2,iphone 15 pro max 512gb,1499990.0,1079990.0,falabella
4,4,iphone 15 pro 128gb,1129990.0,1079990.0,falabella
5,5,iphone 15 256gb,799990.0,719990.0,falabella
9,9,iphone 15 512gb,999990.0,479990.0,falabella
11,11,iphone 15 pro 256gb,1199990.0,819990.0,falabella
13,13,iphone 15 128gb¬†rosado,849990.0,819990.0,paris
14,14,iphone 15 128gb¬†negro,849990.0,819990.0,paris
21,21,iphone 15 plus 128gb¬†rosado,999990.0,949990.0,paris
26,26,iphone 15 128gb¬†azul,849990.0,819990.0,paris
34,34,iphone 15 plus 128gb¬†negro,999990.0,929990.0,paris
38,38,apple iphone 15 pro 5g 128gb,1249990.0,1120800.0,wom
39,39,apple iphone 15 5g 128gb,999990.0,880800.0,wom
40,40,apple iphone 15 pro max 5g 256gb,1499990.0,1348800.0,wom
50,50,iphone 15 negro / 5g / 128 gb / liberado,1099990.0,829990.0,hites
51,51,iphone 15 negro / 5g / 256 gb / liberado,1199990.0,979990.0,hites
52,52,iphone 15 pro max negro / 5g / 256 gb / liberado,1599990.0,1399990.0,hites
53,53,iphone 15 pro negro / 5g / 256 gb / liberado,1499990.0,1249990.0,hites
54,54,iphone 15 / 5g / 512 gb / liberado,1349990.0,1199990.0,hites
57,57,"celular apple iphone 15 128gb 6,1"" negro liber...",1099990.0,849990.0,la polar
59,59,"celular apple iphone 15 pro max 256gb 6,7"" neg...",1699990.0,1299990.0,la polar
60,60,"celular apple iphone 15 pro 256gb 6,1"" negro l...",1599990.0,1199990.0,la polar
61,61,"celular apple iphone 15 256gb 6,1"" negro liber...",1249990.0,949990.0,la polar
62,62,"celular apple iphone 15 512gb 6,1"" negro liber...",1799990.0,999990.0,la polar
63,63,"celular apple iphone 15 pro 512gb 6,1"" negro l...",1899990.0,1349990.0,la polar
64,64,"celular apple iphone 15 plus 256gb 6,7"" black ...",1399990.0,1099990.0,la polar
65,65,apple iphone 15 plus (128 gb) - rosa - distrib...,1099990.0,969990.0,mercado libre
69,69,apple iphone 15 pro (512 gb) - titanio azul - ...,1579990.0,1418990.0,mercado libre
71,71,apple iphone 15 pro max (512 gb) - titanio bla...,1699990.0,1535180.0,mercado libre
72,72,apple iphone 15 plus (512 gb) - negro - distri...,1523090.0,1249990.0,mercado libre
73,73,apple iphone 15 (128 gb) - negro,999990.0,879990.0,mercado libre
75,75,apple iphone 15 plus (128 gb) - verde - distri...,1099990.0,969990.0,mercado libre
77,77,apple iphone 15 plus (256 gb) - rosa - distrib...,1219990.0,101666.0,mercado libre
78,78,apple iphone 15 plus (256 gb) - azul - distrib...,1219990.0,101666.0,mercado libre
81,81,apple iphone 15 plus (256 gb) - verde - distri...,1219990.0,101666.0,mercado libre
82,82,apple iphone 15 plus (512 gb) - amarillo - dis...,1523090.0,1288226.0,mercado libre
83,83,apple iphone 15 plus (128 gb) - verde,1299990.0,1049990.0,mercado libre
87,87,apple iphone 15 pro max (512 gb) - titanio nat...,1699990.0,1469990.0,mercado libre
88,88,iphone 15 128gb negro,979990.0,950590.0,pcfactory
89,89,iphone 15 pro max 256gb 5g titanio negro,1469990.0,1425890.0,pcfactory
90,90,iphone 15 pro max 256gb titanio natural claro,1499490.0,1454490.0,pcfactory
91,91,iphone 15 pro max 256gb titanio negro claro,1499490.0,1454490.0,pcfactory
98,98,iphone 15 pro 5g 512gb negro apple,1729990.0,1359990.0,lider

In [17]:
# Define a function to categorize iPhone models based on their characteristics
def categorize_iphone_model(model):
    model = model.lower()
    if "pro max" in model:
        return "pro max"
    elif "pro" in model:
        return "pro"
    elif "plus" in model:
        return "plus"
    else:
        return "standard"

# Apply the function to the 'modelo' column and create a new 'category' column
df['category'] = df['modelo'].apply(categorize_iphone_model)

# Display the updated dataset with the new 'category' column
df.head()

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda,category,categorias,categor
0,0,iphone 15 pro max 256gb,1349990.0,819990.0,falabella,pro max,pro max,pro max
1,1,iphone 15 128gb,849990.0,819990.0,falabella,standard,standard,standard
2,2,iphone 15 pro max 512gb,1499990.0,1079990.0,falabella,pro max,pro max,pro max
3,3,iphone 11 128gb,429990.0,1079990.0,falabella,standard,standard,standard
4,4,iphone 15 pro 128gb,1129990.0,1079990.0,falabella,pro,pro,pro

In [13]:
# Save the updated DataFrame to a new CSV file
output_file_path = 'final_final_categorias.csv'
df.to_csv(output_file_path, index=False)

output_file_path

'final_final_categorias.csv'

In [ ]:
csv_file = 'final_final_categorias.csv'
df = pd.read_csv(csv_file)

df = df.iloc[1:]

df.columns = ['index', 'modelo', 'precio_normal', 'precio_oferta', 'tienda']

df = df.drop(columns=['index'])


output_csv = 'productosFinal.csv'
df.to_csv(output_csv, index=False)

print(f' {output_csv}')

In [18]:
df1 = pd.read_csv('final_final.csv')
df1

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda
0,0,iphone 15 pro max 256gb,1349990.0,819990.0,falabella
1,1,iphone 15 128gb,849990.0,819990.0,falabella
2,2,iphone 15 pro max 512gb,1499990.0,1079990.0,falabella
3,3,iphone 11 128gb,429990.0,1079990.0,falabella
4,4,iphone 15 pro 128gb,1129990.0,1079990.0,falabella
...,...,...,...,...,...
94,94,iphone 13 5g 256gb gris apple,899990.0,689990.0,lider
95,95,iphone 14 5g 128gb blanco,899990.0,699990.0,lider
96,96,iphone 14 5g 128gb negro,899990.0,699990.0,lider
97,97,iphone 14 plus 5g 256gb blanco apple,1229990.0,889990.0,lider
98,98,iphone 15 pro 5g 512gb negro apple,1729990.0,1359990.0,lider

In [19]:
# Define a function to categorize iPhone models based on their characteristics
def categorize_iphone_model(model):
    model = model.lower()
    if "pro max" in model:
        return "pro max"
    elif "pro" in model:
        return "pro"
    elif "plus" in model:
        return "plus"
    else:
        return "standard"

# Apply the function to the 'modelo' column and create a new 'category' column
df1['categoria'] = df1['modelo'].apply(categorize_iphone_model)

# Display the updated dataset with the new 'category' column
df1.head()

,Unnamed: 0,modelo,precio_normal,precio_oferta,tienda,categoria
0,0,iphone 15 pro max 256gb,1349990.0,819990.0,falabella,pro max
1,1,iphone 15 128gb,849990.0,819990.0,falabella,standard
2,2,iphone 15 pro max 512gb,1499990.0,1079990.0,falabella,pro max
3,3,iphone 11 128gb,429990.0,1079990.0,falabella,standard
4,4,iphone 15 pro 128gb,1129990.0,1079990.0,falabella,pro

In [23]:
# Save the updated DataFrame to a new CSV file
output_file_path = 'final_final_categorias.csv'
df1.to_csv(output_file_path, index=False)

output_file_path

'final_final_categorias.csv'

In [24]:
csv_file = 'final_final_categorias.csv'
df2 = pd.read_csv(csv_file)

df2 = df2.iloc[1:]

df2.columns = ['index', 'modelo', 'precio_normal', 'precio_oferta', 'tienda','categoria']

df2 = df2.drop(columns=['index'])


output_csv = 'productosFinal.csv'
df2.to_csv(output_csv, index=False)

print(f' {output_csv}')

 productosFinal.csv

In [25]:
df3 = pd.read_csv('productosFinal.csv')
df3

,modelo,precio_normal,precio_oferta,tienda,categoria
0,iphone 15 128gb,849990.0,819990.0,falabella,standard
1,iphone 15 pro max 512gb,1499990.0,1079990.0,falabella,pro max
2,iphone 11 128gb,429990.0,1079990.0,falabella,standard
3,iphone 15 pro 128gb,1129990.0,1079990.0,falabella,pro
4,iphone 15 256gb,799990.0,719990.0,falabella,standard
...,...,...,...,...,...
93,iphone 13 5g 256gb gris apple,899990.0,689990.0,lider,standard
94,iphone 14 5g 128gb blanco,899990.0,699990.0,lider,standard
95,iphone 14 5g 128gb negro,899990.0,699990.0,lider,standard
96,iphone 14 plus 5g 256gb blanco apple,1229990.0,889990.0,lider,plus
97,iphone 15 pro 5g 512gb negro apple,1729990.0,1359990.0,lider,pro